- name: Stop and disable systemd service for container-{{ app_name }}
  ansible.builtin.systemd:
    name: container-{{ app_name }}
    state: stopped
    scope: "{{ 'user' if user_account != 'root' else 'system' }}"
    enabled: false
    daemon_reload: true

- name: Remove systemd service file for {{ app_name }}
  ansible.builtin.file:
    path: "{{ '/home/' + user_account + '/.config/systemd/user/container-' + app_name + '.service' if user_account != 'root' else '/etc/systemd/system/container-' + app_name + '.service' }}"
    state: absent

- name: Remove container for {{ app_name }}
  containers.podman.podman_container:
    name: "{{ app_name }}"
    state: absent

# - name: Cleanup old image
#   containers.podman.podman_image:
#     name: "{{ image }}:{{ old_ver }}"
#     state: absent
