---
name: Feature Branch Workflow / Ansible Playbook

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  ansible-playbook-checks:
    name: Ansible Playbook Feature Branch Workflow Checks
    uses: eingram-homelab/reusable_workflows/.github/workflows/_flattened-ansible-f-workflow-checks.yaml@main
    with:
      repository: ${{ github.repository }}
      ref: ${{ github.head_ref || github.ref_name }}
